CREATE TABLE IF NOT EXISTS Product (
  Id int primary key,
  StoreId int,
  Hub int,
  SuCode int,
  ArticleCode int,
  MidasSplitNum int,
  Price int,
  ItmInSellUnt int,
  Promo int,
  UnitId int,
  Rrp int,
  PrevPrc int,
  Por int,
  IsNew int,
  IsDel int,
  LeadTimeStatus int,
  PriceStart int,
  PriceEnd int,
  StoreOrderGroup int,
  LondisOrderGroup int,
);

CREATE TABLE IF NOT EXISTS ProductGroup (
  Id int primary key,
  ArticleCode int,
  MidasSplitNum int,
  PName int,
  CategoryId int,
  PackSize int,
  IsDel int,
  WebParentArticleCode int,
  SuCode int,
  LongName int,
  WeightType int,
  VatRate int,
  Supplier int,
  PackDesc int,
  ImagePaid int,
  OwnBrand int,
  StorageType int,
  ArticleStatus int,
  DelistReason int,
  ParentArticleCode int,
  WebFlag int, 
  LondisProdCd int,
  BudgensProdCd int,
  PriceMarkFlag int,
  ItmInSellUnt int,
  ShelfLife int,
  MasterMidasCode int,
  HfssHigh int,
  ItemWeightVol int,
  ItemUnit int
);

CREATE TABLE IF NOT EXISTS Customer (
  Id int primary key,
  CustNo int,
  WebBranchId int,
  HomeBranch int,
  Title int,
  Surname int,
  FirstName int,
  TradingName int,
  Street2 int,
  Street3 int,
  HouseNumber int,
  Street int,
  Street4 int, 
  Street5 int,
  City int,
  District int,
  PostCode int,
  Telephone int,
  MobilePhone int,
  Fax int,
  EmailAddress int,
  ConPrefMail int,
  ConPrefTelephone int,
  ConPrefEmail int,
  ConPrefMobile int,
  Licenced int,
  CanShop int,
  CanDeliver int,
  FaciaType int,
  Classification int,
  BusinessType int,
  GroupSector int,
  IsDel int,
  Status int,
  OnstopFlag int,
  SopFlag int,
  NacNo int,
  DsVddFlag int,
  UseProdCd int,
  BrpCustNo int,
  BrpLeafletScheme int,
  SalesmanCode int,
  TobaccoClub int,
  CountryCode int
);

CREATE TABLE IF NOT EXISTS CustCredit (
  Id int primary key,
  CustomerNumber int,
  CustomersTotalCreditLimit int,
  OverallCreditLimitStatus int,
  PaymentDayNumber int,
  NoOfCreditDays int,
  ExtendedCreditDays int,
  NoOfWeeksCredit int,
  FirstPaymentDate int,
  Terms int,
  VddEmail int,
  Bacs int,
  Kyc int,
  Dd int
);

CREATE TABLE IF NOT EXISTS StdPrice (
  Id int primary key,
  "Date" int,
  CountryCode int,
  DepotNumber int,
  ChildArticleCode int,
  SaleableUnitCode int,
  WeightType int,
  NumberOfItemsInACase int,
  PromoIndicator int,
  WspCollectPrice int,
  LocalPriceIndicator int,
  StandardWspMidasField int,
  StandardWspDeliveredMidasField int,
  StartDate int,
  EndDate int,
  DeliveredPrice int,
  OnlineExcPrice int, 
  ClickAndCollectPrice int,
  Spare int,
  RecommendedRetailPrice int,
  Por int,
  DeliveredPor int,
  OnlineExclusivePor int,
  ClickAndCollectPor int,
  SparePor int,
  MupWspCollectPrice int,
  MupDeliveredPrice int,
  MupOnlineExclusive int,
  MupClickAndCollect int,
  MupSpare int,
  PromotionNo int,
  PromCollectWsp int,
  PromDeliveredPrice int,
  PromOnlineExclusive int,
  PromClickAndCollect int,
  PromSpare int,
  PrePromotionPriceWsp int,
  PrePromotionPriceDelivered int,
  PrePromotionPriceOe int,
  PrePromotionPriceClickAndCollect int,
  PrePromotionPriceSpare int,
  RecommendedRetailPrice int,
  Por int,
  DeliveredPor int,
  OnlineExclusivePor int,
  ClickAndCollectPor int,
  SparePor int,
  PromStartDate int,
  PromEndDate int
);

CREATE TABLE IF NOT EXISTS FasPrice (
  Id int primary key,
  Date int,
  CountryCode int,
DepotNumber int,
ChildArticleCode int,
SaleableUnitCode int,
WeightType int,
NumberOfItemsInACase int,
FasciaCode int,
PromotionNo int,
WspCollectPrice int,
WspDeliveredPrice int,
WspOnlineExclusive int,
WspClickAndCollectPrice int,
WspSpare4 int,
PrePromotionPriceWsp int,
PrePromotionPriceDelivered int,
PrePromotionPriceOE int,
PrePromotionPriceClickAndCollect int,
PrePromotionPriceSpare4 int,
RecommendedRetailPrice int,
Por int,
DeliveredPor int,
OnlineExclusivePor int,
ClickAndCollectPor int,
SparePor int,
PromotionStart int,
PromotionEnd int
);

CREATE TABLE IF NOT EXISTS ClbPrice (
  Id int primary key,
  Date int,
CountryCode int,
DepotNumber int,
ChildArticleCode int,
SaleableUnitCode int,
WeightType int,
NumberOfItemsInACase int,
Club int,
WspCollectPrice int,
WspDeliveredPrice int,
WspOEPrice int,
WspClickAndCollectPrice int,
WspSpare4 int,
RecommendedRetailPrice int,
Por int,
DeliveredPor int,
OEPor int,
ClickAndCollectPor int,
SparePor int,
StartDate int,
EndDate int
);

CREATE TABLE IF NOT EXISTS SpendAndSave (
  Id int primary key,
  PeriodNo int,
  CustomerNo int,
  Linked int,
  TotalSpend int,
  TobTotalSpend int,
  NonTobTotalSpend int,
  CurrBandNTob int,
  TotalRebate,NTobSpendToNextBand int,
  EndOfPeriodDate int,
  NextBandNTobPct int,
  ExtraRebate int,
  NextBandNTob int,
  LastTradeDate int,
  MaximumBandSize int,
  CurrBandNTobDec int,
  LpTotalSpend int,
  LPTobTotalSpend int,
  LPNonTobTotalSpend int,
  LpCurrBandNTob int,
  LpTotalRebate int,
  TescoTotalRebate int,
  TescoLpTotalRebate int,
  TescoCurrBand int,
  TescoLpBand int,
  TescoCurrSpend int,
  TescoLpTotalSpend int,
  TescoCurrQualifyingSpend int,
  TescoLpQualifyingSpend int,
  TescoPeriodNo int,
  TescoEndOfPeriodDate int,
  TescoEndOfDataChar int,
  StartOfPeriodDate int,
  LastPeriodStartDate int,
  LastPeriodEndDate int
);